---
- hosts: localhost
  connection: local
  vars:
    PHP_CONFIG_FILES:
      - /etc/php/7.0/fpm/php.ini
      - /etc/php/7.0/cli/php.ini
    LIBRENMS_PHP_TZ: "{{ lookup('env', 'LIBRENMS_PHP_TZ') | default('US/Pacific', true) }}"
    LIBRENMS_SNMPD_GROUP_NAME: "{{ lookup('env', 'LIBRENMS_SNMPD_GROUP_NAME') | default('MyROGroup', true) }}"
    LIBRENMS_SNMPD_GROUP_SECRET: "{{ lookup('env', 'LIBRENMS_SNMPD_GROUP_SECRET') | mandatory }}"
    LIBRENMS_SNMPD_CONTACT_NAME: "{{ lookup('env', 'LIBRENMS_SNMPD_CONTACT_NAME') | default('Your Name', true) }}"
    LIBRENMS_SNMPD_CONTACT_EMAIL: "{{ lookup('env', 'LIBRENMS_SNMPD_CONTACT_EMAIL') | default('your@email.address', true) }}"
  tasks:
    - name: configure php timezone
      lineinfile:
        dest: "{{ item }}"
        regexp: ^[;\s]*date\.timezone\s+=
        line: date.timezone = "{{ LIBRENMS_PHP_TZ }}"
        state: present
      with_items: "{{ PHP_CONFIG_FILES }}"

    - name: set /opt/librenms/rrd permissions
      file:
        dest: /opt/librenms/rrd
        state: directory
        mode: 0775

    - name: Configure /opt/librenms permissions
      command: chown -R librenms:librenms /opt/librenms

    - name: Configure mysql client
      lineinfile:
        dest: /etc/mysql/conf.d/mysql.cnf
        regexp: ^[\s#]*sql_mode\s*=
        line: sql_mode=''
        state: present

    - name: Configure snmpd
      copy:
        dest: /etc/snmp/snmpd.conf
        content: |
          com2sec readonly  default         {{ LIBRENMS_SNMPD_GROUP_SECRET }}
          
          group {{ LIBRENMS_SNMPD_GROUP_NAME }} v2c        readonly
          view all    included  .1                               80
          access {{ LIBRENMS_SNMPD_GROUP_NAME }} ""      any       noauth    exact  all    none   none
          
          syslocation Rack, Room, Building, City, Country [GPSX,Y]
          syscontact {{ LIBRENMS_SNMPD_CONTACT_NAME }} <{{ LIBRENMS_SNMPD_CONTACT_EMAIL }}>
          
          #Distro Detection
          extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro

